language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-12
      - libgtest-dev

before_script:
  - export CC=gcc-12
  - export CXX=g++-12

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest